aider: Added `debug` function to handle debug messages and prevent `NameError`.
# Aider chat conversation:

USER: Traceback (most recent call last):
  File "/Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py", line 227, in <module>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py", line 207, in main
    files_with_secrets = [f for f in args.filenames if not is_excluded(f, EXCLUDE_PATTERNS) and contains_secret(f, hook_id)]
                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py", line 136, in contains_secret
    debug(0, "File is already encrypted with SOPS: {}".format(filename))
    ^^^^^
NameError: name 'debug' is not defined
Traceback (most recent call last):
  File "/Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py", line 227, in <module>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py", line 207, in main
    files_with_secrets = [f for f in args.filenames if not is_excluded(f, EXCLUDE_PATTERNS) and contains_secret(f, hook_id)]
                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py", line 136, in contains_secret
    debug(0, "File is already encrypted with SOPS: {}".format(filename))
    ^^^^^
NameError: name 'debug' is not defined

ASSISTANT: It appears that the `debug` function is being called but is not defined in the `forbid_secrets.py` file. To resolve this issue, we need to define the `debug` function. Here is the diff for the changes:

```diff
--- hooks/forbid_secrets.py
+++ hooks/forbid_secrets.py
@@ ... @@
+DEBUG_LEVEL = 0  # Set the desired debug level here, 0 for no debug output

+def debug(level, message):
+    """
+    Prints a debug message with a given level.
+    """
+    if level <= DEBUG_LEVEL:
+        print("DEBUG: {}".format(message))
+
@@ ... @@
-    debug(0, "File is already encrypted with SOPS: {}".format(filename))
+    debug(0, "File is already encrypted with SOPS: {}".format(filename))
```

In the above diff, I've added a `DEBUG_LEVEL` constant and a `debug` function that checks if the provided debug level is less than or equal to `DEBUG_LEVEL` and prints the message if the condition is true. The `DEBUG_LEVEL` constant can be set to the desired level of debug output. The `debug` function is now defined and will not cause a `NameError`.